export class Member {
  constructor(public id: string,
              public title: string,
              public short_title: string,
              public api_uri: string,
              public first_name: string,
              public middle_name: string,
              public last_name: string,
              public suffix: string,
              public date_of_birth: string,
              public gender: string,
              public party: string,
              public leadership_role: string,
              public twitter_account: string,
              public facebook_account: string,
              public youtube_account: string,
              public govtrack_id: number,
              public cspan_id: number,
              public google_entity_id: string,
              public fec_candidate_id: string,
              public url: string,
              public rss_rul: string,
              public contact_form: string,
              public in_office: boolean,
              public dw_nominate: number,
              public ideal_point: string,
              public seniority: number,
              public next_election: number,
              public total_votes: number,
              public total_present: number,
              public ocd_id: string,
              public office: string,
              public phone: string,
              public fax: string,
              public senate_class: number,
              public state_rank: string,
              public state: string,
              public lis_id: number,
              public missed_votes_pct: number,
              public votes_with_party_pct: number,
              public prof: string

              ) {}
}
